#!/bin/bash
echo "$(date '+%Y-%m-%d %H:%M:%S') - HOOK: $1 $2 $3 $4" >> /tmp/libvirt-hook.log

DOMAIN="$1"
OPERATION="$2"
PHASE="$3"

if [ "$DOMAIN" = "Win11" ]; then
  if [ "$OPERATION" = "release" ] && [ "$PHASE" = "end" ]; then
      echo "GPU RESET TRIGGERED" >> /tmp/libvirt-hook.log
      sleep 2
      echo 1 > /sys/bus/pci/devices/0000:06:00.0/remove 2>/dev/null
      sleep 5
      echo 1 > /sys/bus/pci/devices/0000:06:00.1/remove 2>/dev/null
      sleep 10
      echo 1 > /sys/bus/pci/rescan
      sleep 10
  fi
fi
